# Generated by Django 4.2.1 on 2023-06-08 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_commentlike_comments_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='parent_comment',
        ),
    ]
