# Generated by Django 4.2.1 on 2023-05-30 11:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default_profile_pic.png', upload_to='profile_pics')),
                ('first_name', models.CharField(default='John', max_length=30)),
                ('last_name', models.CharField(default='Appleseed', max_length=36)),
                ('date_of_birth', models.DateField(default='1900-01-01')),
                ('bio', models.TextField(blank=True)),
                ('email', models.EmailField(default='johnappleseed@example.com', max_length=254)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
