# Generated by Django 4.2.1 on 2023-06-08 17:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key='True', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('image', models.ImageField(default='default_profile_pic.png', upload_to='profile_pics')),
                ('first_name', models.CharField(default='--', max_length=30, null=True)),
                ('last_name', models.CharField(default='--', max_length=36)),
                ('date_of_birth', models.DateField(blank=True, default=None, null=True)),
                ('bio', models.TextField(blank=True)),
                ('email', models.EmailField(default='--', max_length=254)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
