# Generated by Django 4.2.1 on 2023-05-26 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_user_profile_user1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user1',
            new_name='user',
        ),
    ]
