# Generated by Django 4.2.1 on 2023-06-12 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.IntegerField(blank=True, choices=[(1, 'New Post'), (2, 'Comment'), (3, 'Like'), (4, 'Message')], null=True),
        ),
    ]
